### ISSUE TITLE
Question: Does it support async dependencies?

### ISSUE THREAD

**Issue by Vanethos** [aloisdeniel/dioc#10]
Hi there.

I'm trying to incorporate DI into my project, since handling all dependencies by hand gets crazy after a while.

However, I have two problems:

First one is that I have instances like this:

```
Future<SharedPreferences> getSharedPreferences() {
  return SharedPreferences.getInstance();
}

ProjectSharedPrefs getSharedPrefs(SharedPreferences sharedPrefs) {
  return SharedPrefs(sharedPrefs);
}
```

Where to obtain `ProjectSharedPrefs` I would have to wait for the `Future` from `SharedPreferences.getInstance()`

The other one concerns `Dio` interceptors, that I have to create asynchronously, so to get that dependency I will have a `Future<Dio>`. Maybe this is not the best option, but I could not find a way of processing async methods to put data into the headers while at the same time initializing Dio.

With `dioc` could I solve this and the generator would handle this?

Thank you for your time.

**Comment by aloisdeniel** [comment]
Sorry for the late answer ... but did you try registering a `Future<SharedPreferences>` into the container ?

I will probably not introduce specific asynchronous unless I migrate everything to async.

**Comment by Vanethos** [comment]
Hi!

Sorry for late answer too ahaha

I will have to test this in the future. In my case, since I was starting a new project, I decided not to use dioc, in the future I will for sure test it

thanks!
