### ISSUE TITLE
Container conflicts with flutter/material.dart

### ISSUE THREAD

**Issue by eopeter** [aloisdeniel/dioc#3]
implementing for Flutter and getting this error in main.dart that imports flutter/material.dart

error: The name 'Container' is defined in the libraries 'container.dart' and 'container.dart'.

Any ideas on how to resolve without removing flutter/material.dart?

**Comment by aloisdeniel** [comment]
You can specify a library prefix for that use case :

```dart
import 'package:dioc/dioc.dart' as dioc;

final container = dioc.Container();
```
