### ISSUE TITLE
Flutter dependency conflicts

### ISSUE THREAD

**Issue by jromero** [aloisdeniel/dioc#8]
build_runner conflicts with flutter 0.9.4 

Due to:
https://github.com/aloisdeniel/dioc/blob/2b0695ca98652230fe361baf65c8562c4f2dff87/dioc_generator/pubspec.yaml#L17

I'm getting this issue:
> Because dioc_generator >=0.1.0 depends on build_runner ^0.10.1+1 and phrase_flutter depends on build_runner ^1.0.0, dioc_generator >=0.1.0 is forbidden.
> So, because phrase_flutter depends on dioc_generator ^0.1.2, version solving failed

**Comment by edgarfgp** [comment]
I fix this issue reading this article https://iirokrankka.com/2018/08/28/resolving-dart-package-version-conflicts/

**Comment by hoangcao10** [comment]
same issue

**Comment by edgarfgp** [comment]
Did you try  build_runner: any ?

**Comment by hoangcao10** [comment]
yes, i did

**Comment by hoangcao10** [comment]
> Did you try build_runner: any ?

Yes, I did

**Comment by aloisdeniel** [comment]
Thanks for reporting this!

Updated dependencies and published a [new 0.1.5 version](https://pub.dartlang.org/packages/dioc_generator).

Is it better now ?

**Comment by eaglestorm** [comment]
There is still an issue with the versions.  The latest version requires analyzer 0.33.0  which is used by flutter_test

**Comment by eaglestorm** [comment]
Ok the issue fixed itself when I upgraded to the latest version flutter.
